language: groovy

install:
  - chmod +x shscripts/*
  - shscripts/env.sh

script:
  - ./gradlew -s check

after_success:
  - ./gradlew -s artifactoryPublish
  - ./gradlew -s bintrayUpload
  - ./gradlew -s publishPlugins

branches:
  only:
    - master
